### ISSUE TITLE
有Build好的么。。。。

### ISSUE THREAD

**Issue by sylingd** [unknwon/qiniudrive#1]
自己尝试Build了半天也不成功

来求一下已经Build好的版本~谢谢

**Comment by unknwon** [comment]
应该可能没有。。吧。。好久没碰这代码了。。不知道之前的二进制丢哪儿了。。

**Comment by sylingd** [comment]
呃。。。。

**Comment by duguying** [comment]
@abc896640547 将libs.rar解压，重新导入引用。然后编译。
给你一个build好了的http://duguying.qiniudn.com/qiniudrive-master.zip

**Comment by sylingd** [comment]
@duguying 多谢
